### ISSUE TITLE
Problem with Lager when running 'mix deps.get'

### ISSUE THREAD

**Issue by daraclare** [ineedthis/phoenix-starter#7]
Hi, I have tried to run mix deps.get and get the following error regarding deps/lager: 

➜  phoenix-starter git:(master) ✗ mix deps.get                       
- Getting lager (git://github.com/basho/lager.git)
  Cloning into '/Users/dara/Sites/phoenix-starter/deps/lager'...
  fatal: unable to connect to github.com:
  github.com[0: 192.30.252.128]: errno=Operation timed out

*\* (Mix) Command "git clone --no-checkout --progress "git://github.com/basho/lager.git" "/Users/dara/Sites/phoenix-starter/deps/lager"" failed
➜  phoenix-starter git:(master) ✗

**Comment by mjcloutier** [comment]
Very late reply. I stopped working on the app, after pushing it up 6 months ago. Gonna revive project since a ton more Elixir/Phoenix contributions and simple drop in solutions. Can try pulling the latest project if still interested in checking out the project and let me know if any issues. Thanks.
